#
# Build stage
#
FROM maven:4.0.0-jdk-17-slim AS build
COPY src /home/app/src
COPY pom.xml /home/app
WORKDIR /home/app
RUN mvn clean package

#
# Package stage
#
FROM openjdk:17-jre-slim
COPY --from=build /home/app/target/comicapi-0.0.1-SNAPSHOT.jar /usr/local/lib/demo.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/usr/local/lib/demo.jar"]
